In [2]:
#importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
#importing the models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [5]:
#data collection
heart_data = pd.read_csv('/content/heart.csv')

In [6]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
heart_data.shape

(303, 14)

In [8]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [9]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
#splitting target and features
X = heart_data.drop(columns ='target',axis =1)
Y = heart_data['target']

In [11]:
print(X)
print(Y)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [12]:
#1st TRAIN_TEST_SPLIT
#splitting the data into training data and testing data
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.1,stratify=Y,random_state=3)

In [13]:
# creating a list to add all the models because training and testing the models individually takes more time so we are going to use a loop function

models = [LogisticRegression(max_iter=1000),SVC(kernel= 'linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [14]:
#CREATING A function
def compare_models_train_test():

  for model in models:
    model.fit(X_train,Y_train)
    model_prediction = model.predict(X_test)
    accuracy = accuracy_score(model_prediction,Y_test)
    print('acccuracy of the',model,'=' ,accuracy)

In [15]:
#calling the function
compare_models_train_test()

acccuracy of the LogisticRegression(max_iter=1000) = 0.8387096774193549
acccuracy of the SVC(kernel='linear') = 0.8064516129032258
acccuracy of the KNeighborsClassifier() = 0.6451612903225806
acccuracy of the RandomForestClassifier() = 0.7419354838709677

#**CROSS VALIDATION COMES IN**

In [16]:
#logistic regression
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000),X,Y,cv=5)
print(cv_score_lr)
mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr = mean_accuracy_lr*100
mean_accuracy_lr = round(mean_accuracy_lr,2)
print(mean_accuracy_lr)

[0.80327869 0.8852459  0.85245902 0.86666667 0.75      ]
83.15

SINGLE CALL

In [17]:
models = [LogisticRegression(max_iter=1000),SVC(kernel= 'linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [18]:
#defining a function
def compare_models_cross_validation():
  for model in models:
    cv_score = cross_val_score(model,X,Y, cv=5)
    accuracy = sum(cv_score)/len(cv_score)
    accuracy = accuracy*100
    accuracy = round(accuracy,2)
    print('accuracy of the',model,':' ,accuracy)
    print('______________________________________________________')

In [19]:
compare_models_cross_validation()

accuracy of the LogisticRegression(max_iter=1000) : 83.15
______________________________________________________
accuracy of the SVC(kernel='linear') : 82.83
______________________________________________________
accuracy of the KNeighborsClassifier() : 64.39
______________________________________________________
accuracy of the RandomForestClassifier() : 81.51
______________________________________________________